- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

- name: PostgreSQL | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{ db_user }}"
    db: "{{ db_name }}"
    password: "{{ db_password }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
  no_log: true
  become: yes
  become_user: "{{postgresql_admin_user}}"
